swagger: '2.0'
info:
  title: tetra api
  description: tetra is a test results aggregator
  version: '0.0.1'
produces:
  - application/json
paths:
  /projects:
    get:
      summary: List projects
      responses:
        200:
          description: A list of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/ProjectResponse'
    post:
      summary: Create project
      parameters:
        - name: project
          in: body
          description: The project to create
          required: true
          schema:
            $ref: '#/definitions/ProjectRequest'
      responses:
        201:
          description: The created project
          schema:
            $ref: '#/definitions/ProjectResponse'
  /{project_id}/suites:
    parameters:
      - name: project_id
        in: path
        description: The project id
        type: integer
        required: true
    get:
      summary: List suites
      responses:
        200:
          description: The list of suites
          schema:
            type: array
            items:
              $ref: '#/definitions/SuiteResponse'
    post:
      summary: Create suite
      parameters:
        - name: suite
          in: body
          description: The suite to create
          required: true
          schema:
            $ref: '#/definitions/SuiteRequest'
      responses:
        201:
          description: The created suite
          schema:
            $ref: '#/definitions/SuiteResponse'
  /{project_id}/suites/{suite_id}:
    parameters:
      - name: project_id
        in: path
        description: The project id
        type: integer
        required: true
      - name: suite_id
        in: path
        description: The suite id
        type: integer
        required: true
    get:
      summary: Get suite
      responses:
        200:
          description: The fetched suite
          schema:
            $ref: '#/definitions/SuiteResponse'
    delete:
      summary: Delete suite
      responses:
        204:
          description: An empty response
  /{project_id}/suites/{suite_id}/builds:
    parameters:
      - name: project_id
        in: path
        description: The project id
        type: integer
        required: true
      - name: suite_id
        in: path
        description: The suite id
        type: integer
        required: true
    get:
      summary: Get builds
      responses:
        200:
          description: The list of builds
          schema:
            type: array
            items:
              $ref: '#/definitions/BuildResponse'
    post:
      summary: Create build
      responses:
        201:
          description: The created build
          schema:
            $ref: '#/definitions/BuildResponse'
  /{project_id}/suites/{suite_id}/builds/{build_num}/results:
    parameters:
      - name: project_id
        in: path
        description: The project id
        type: integer
        required: true
      - name: suite_id
        in: path
        description: The suite id
        type: integer
        required: true
      - name: build_num
        in: path
        description: The suite id
        type: integer
        required: true
    get:
      summary: Get results
      responses:
        200:
          description: The build results
          schema:
            $ref: '#/definitions/ResultListResponse'
    post:
      summary: Create result
      responses:
        201:
          description: The created result
          schema:
            $ref: '#/definitions/ResultResponse'

definitions:
  ProjectResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  ProjectRequest:
    type: object
    properties:
      name:
        type: string
  SuiteRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
  SuiteResponse:
    type: object
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      project_id:
        type: integer
  BuildResponse:
    type: object
    properties:
      build_num:
        type: integer
      id:
        type: integer
      project_id:
        type: integer
      results:
        $ref: '#/definitions/ResultListMetadata'
      suite_id:
        type: integer
      timestamp:
        type: integer

  ResultListResponse:
    type: object
    properties:
      metadata:
        $ref: '#/definitions/ResultListMetadata'
      results:
        type: array
        items:
          $ref: '#/definitions/ResultResponse'
  ResultListMetadata:
    type: object
    properties:
      success_rate:
        type: integer
      total_errors:
        type: integer
      total_failures:
        type: integer
      total_passed:
        type: integer
      total_results:
        type: integer
      total_skipped:
        type: integer
  ResultResponse:
    type: object
    properties:
      build_name:
        type: integer
      build_url:
        type: string
      environment:
        type: string
      extra_data:
        type: string
      id:
        type: integer
      project_id:
        type: integer
      region:
        type: string
      result:
        type: string
      result_message:
        type: string
      suite_id:
        type: integer
      test_name:
        type: string
      timestamp:
        type: integer
